name: Release Sherlock Platform prebuilt

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-platform:
    uses: ./.github/workflows/build.yml

  release:
    needs: build-platform
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get SherlockPlatformApplicationInfo.xml Version
        id: get_xml_version
        run: |
          XML_VERSION=$(python ../scripts/get_version.py)
          echo "xml_version=$XML_VERSION" >> $GITHUB_OUTPUT

      - name: Download Artifacts from Build Workflow
        uses: actions/download-artifact@v4
        with:
          path: sherlock-platform-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_xml_version.outputs.xml_version }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            build-artifacts/sherlock-platform-linux-*/sherlock-platform.tar.gz#sherlock-platform-${{ steps.get_xml_version.outputs.xml_version }}.tar.gz
            build-artifacts/sherlock-platform-mac-*/sherlock-platform.mac.aarch64.zip#sherlock-platform.mac.aarch64-${{ steps.get_xml_version.outputs.xml_version }}.zip
            build-artifacts/sherlock-platform-win-*/sherlock-platform.win.zip#sherlock-platform.win-${{ steps.get_xml_version.outputs.xml_version }}.zip
            build-artifacts/sherlock-platform-sources-*/sherlock-platform-sources.zip#sherlock-platform-sources-${{ steps.get_xml_version.outputs.xml_version }}.zip