name: Release Sherlock Platform prebuilt

on:
  release:
    types: [created, edited, published, prereleased, released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0, v1.0, v1.2.3-dev)'
        required: true
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-platform:
    uses: ./.github/workflows/build.yml

  release:
    needs: build-platform
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts from Build Workflow
        uses: actions/download-artifact@v4
        with:
          path: sherlock-platform-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name || inputs.release_tag }}
          prerelease: ${{ github.event.release.prerelease || inputs.prerelease }}
          files: |
            sherlock-platform-artifacts/*/*
